project_id = "fygccvobsjaubkbidavq"

[functions.extract-client-data]
verify_jwt = false

[functions.generate-contract]
verify_jwt = false

[functions.analyze-template]
verify_jwt = false

[functions.send-to-autentique]
verify_jwt = false

[functions.render-contract-docx]
verify_jwt = false

[functions.pipefy-card-moved]
verify_jwt = false